# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 669b60b640fda7c153c83f4729bd321ec5af2e5752cac7b932eb45a510301f46a8d5bcc7439ffbe0ed933beae7c5e8b7b85e81579f98af259394159dccc1a13d

test:
  secret_key_base: 6a1906303892e04407b5e53931baceaec93174cfadd3a160686e5af140bb65fe66ba462936c348b3ee974964209853a02a4c9ffd3216a796912c4c6f75772fb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
